[package]
name = "png-to-bits"
version = "1.0.0"
authors = ["Edwin Svensson <png_to_bits@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = [ "yaml" ] }
png = "0.16"

