[package]
name = "png-to-bits"
version = "0.1.0"
authors = ["Edwin Svensson <png-to-bits@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
png = "0.16"

